In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

Создать одномерный массив Numpy под названием a из 12 последовательных
целых чисел чисел от 12 до 24 невключительно

In [2]:
a=np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [26]:
a1=a.reshape(2, 6)
a2=a.reshape(3, 4)
a3=a.reshape(12, 1)
a4=a.reshape(6, 2)
a5=a.reshape(4, 3)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [ ]:
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 
(в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
a1=a.reshape(2, -1)
a2=a.reshape(3, -1)
a3=a.reshape(-1, 1)
a4=a.reshape(-1, 2)
a5=a.reshape(4, -1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [ ]:
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
Сравним два  массива: 1 - созданный reshape от двумерного, 2 -  одномерный 

In [6]:
а=np.arange(12, 24)
x = a.reshape(3,4)
b = x.reshape(12,1)
print(a)
print(b)

[12 13 14 15 16 17 18 19 20 21 22 23]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Вывод:одномрный массив и масив Nampy различаются. Последний выводится как двумерный массив с двумя [].

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального
распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [12]:
c = np.random.randn(3,4)
c

array([[ 0.32605518, -1.2010459 ,  0.06847676,  0.53222186],
       [-1.48706251,  1.21285012,  0.54308154,  1.05025763],
       [-1.12533596, -1.1604163 , -0.11319312,  1.29759722]])

In [13]:
print(c.size)

12


In [17]:
d=c.flatten()
print(d.size)
d

12


array([ 0.32605518, -1.2010459 ,  0.06847676,  0.53222186, -1.48706251,
        1.21285012,  0.54308154,  1.05025763, -1.12533596, -1.1604163 ,
       -0.11319312,  1.29759722])

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [19]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно 
с интервалом 2. В чем разница между массивами a и b?


In [20]:
b = np.arange(20, 1, -2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Ответ: а - одномерный, b - двумерный (две [])

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1
меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут
size, равный 10.

In [23]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [24]:
b = np.ones((3, 2)) +1
b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [25]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [2., 2.]])

In [26]:
a.shape, b.shape, v.shape

((2, 2), (3, 2), (5, 2))

In [28]:
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), 
состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. 
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [29]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [34]:
B = np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [35]:
B.size

16

In [36]:
B.shape

(4, 4)

Получится ли вычислить обратную матрицу для матрицы B и почему?

In [37]:
B_inv = np.linalg.inv(B)
B_inv

LinAlgError: Singular matrix

Ответ: ен получится, т.к. В - сингулярная матрица

10 Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [40]:
np.random.seed(42)

11 Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных
целых чисел от 0 до 16 невключительно. 

In [41]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

12 Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив
матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу
D_inv для D.

In [42]:
C = c.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [44]:
D = B + C*10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [45]:
d = np.linalg.det(D)
d

-28511999.999999944

оределитель равен -28511999.999999944

In [46]:
rang = np.linalg.matrix_rank(D)
rang

4

In [47]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

13 Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
Убедитесь, что в матрице D_inv остались только нули и единицы. 
С помощью функции numpy.where, используя матрицу D_inv в качестве маски, 
а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент
матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [48]:
D_inv = np.where(D_inv < 0, 0, 1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [49]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [50]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [51]:
E = np.where(D_inv == 1, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])